version: '3'
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ../custom_components:/config/custom_components
      - ..:/workspace
    environment:
      - PYTHONBREAKPOINT=ipdb.set_trace
    ports:
      - "8123:8123"
    command: >
      sh -c "pip install ipdb debugpy
      && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m homeassistant --config /config --debug"